// export const SET_BRANDS = "SET_BRANDS";
// export const SET_CATEGORIES = "SET_CATEGORIES";
// export const SET_COLORS = "SET_COLORS";
// export const SET_DATA = "SET_DATA";
// export const SET_MAX_PRICE = "SET_MAX_PRICE";
// export const SET_MIN_PRICE = "SET_MIN_PRICE";

// export const SET_SELECTED_CHECKBOXES = "SET_SELECTED_CHECKBOXES";
// export const SET_LEFT_SIDE_MOBILE_IS_OPEN = "SET_LEFT_SIDE_MOBILE_IS_OPENS";
// export const SET_RIGHT_SIDE_MOBILE_IS_OPEN = "SET_RIGHT_SIDE_MOBILE_IS_OPENS";
// export const SET_TOGGLE = "SET_TOGGLE";
// export const SET_IS_MOBILE = "SET_IS_MOBILE";

// export const SET_SORT_BY = "SET_SORT_BY";
// export const GET_PRODUCTS = "GET_PRODUCTS";
// export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
// export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
// export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
// export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
