export const SET_SEARCHED_DATA = "SET_SEARCHED_DATA";
export const SET_SEARCH_SUBMITTED = "SET_SEARCH_SUBMITTED";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

